# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(938, 711)
        self.pushButton_Cargar_Dataset = QtWidgets.QPushButton(Form)
        self.pushButton_Cargar_Dataset.setGeometry(QtCore.QRect(510, 130, 421, 23))
        self.pushButton_Cargar_Dataset.setObjectName("pushButton_Cargar_Dataset")
        self.groupBox_Separadores = QtWidgets.QGroupBox(Form)
        self.groupBox_Separadores.setGeometry(QtCore.QRect(560, 10, 361, 101))
        self.groupBox_Separadores.setObjectName("groupBox_Separadores")
        self.radioButton_Coma = QtWidgets.QRadioButton(self.groupBox_Separadores)
        self.radioButton_Coma.setGeometry(QtCore.QRect(10, 30, 99, 21))
        self.radioButton_Coma.setObjectName("radioButton_Coma")
        self.radioButton_Pipe = QtWidgets.QRadioButton(self.groupBox_Separadores)
        self.radioButton_Pipe.setGeometry(QtCore.QRect(120, 30, 99, 21))
        self.radioButton_Pipe.setObjectName("radioButton_Pipe")
        self.radioButton_P_Coma = QtWidgets.QRadioButton(self.groupBox_Separadores)
        self.radioButton_P_Coma.setGeometry(QtCore.QRect(10, 60, 131, 21))
        self.radioButton_P_Coma.setObjectName("radioButton_P_Coma")
        self.radioButton_Hashtag = QtWidgets.QRadioButton(self.groupBox_Separadores)
        self.radioButton_Hashtag.setGeometry(QtCore.QRect(190, 60, 99, 21))
        self.radioButton_Hashtag.setObjectName("radioButton_Hashtag")
        self.radioButton_Dos_Puntos = QtWidgets.QRadioButton(self.groupBox_Separadores)
        self.radioButton_Dos_Puntos.setGeometry(QtCore.QRect(230, 30, 111, 21))
        self.radioButton_Dos_Puntos.setObjectName("radioButton_Dos_Puntos")
        self.tableWidget_Dataset = QtWidgets.QTableWidget(Form)
        self.tableWidget_Dataset.setGeometry(QtCore.QRect(20, 270, 901, 261))
        self.tableWidget_Dataset.setObjectName("tableWidget_Dataset")
        self.tableWidget_Dataset.setColumnCount(0)
        self.tableWidget_Dataset.setRowCount(0)
        self.pushButton_Buscar_Dataset = QtWidgets.QPushButton(Form)
        self.pushButton_Buscar_Dataset.setGeometry(QtCore.QRect(20, 20, 141, 23))
        self.pushButton_Buscar_Dataset.setObjectName("pushButton_Buscar_Dataset")
        self.label_Ruta_Dataset = QtWidgets.QLabel(Form)
        self.label_Ruta_Dataset.setGeometry(QtCore.QRect(30, 60, 481, 16))
        self.label_Ruta_Dataset.setObjectName("label_Ruta_Dataset")
        self.horizontalSlider_Test_Entrenamiento = QtWidgets.QSlider(Form)
        self.horizontalSlider_Test_Entrenamiento.setGeometry(QtCore.QRect(20, 200, 431, 16))
        self.horizontalSlider_Test_Entrenamiento.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Test_Entrenamiento.setObjectName("horizontalSlider_Test_Entrenamiento")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 160, 51, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(360, 160, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_Vector = QtWidgets.QLabel(Form)
        self.label_Vector.setGeometry(QtCore.QRect(30, 600, 821, 16))
        self.label_Vector.setObjectName("label_Vector")
        self.pushButton_Vector = QtWidgets.QPushButton(Form)
        self.pushButton_Vector.setGeometry(QtCore.QRect(40, 560, 151, 23))
        self.pushButton_Vector.setObjectName("pushButton_Vector")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_Cargar_Dataset.setText(_translate("Form", "Cargar Dataset"))
        self.groupBox_Separadores.setTitle(_translate("Form", "Separadores"))
        self.radioButton_Coma.setText(_translate("Form", "Coma (,)"))
        self.radioButton_Pipe.setText(_translate("Form", "Pipe (|)"))
        self.radioButton_P_Coma.setText(_translate("Form", "Punto y coma (;)"))
        self.radioButton_Hashtag.setText(_translate("Form", "Hashtag (#)"))
        self.radioButton_Dos_Puntos.setText(_translate("Form", "Dos Puntos (:)"))
        self.pushButton_Buscar_Dataset.setText(_translate("Form", "Buscar Dataset"))
        self.label_Ruta_Dataset.setText(_translate("Form", "Ruta Dataset"))
        self.label_2.setText(_translate("Form", "Test"))
        self.label_3.setText(_translate("Form", "Entrenamiento"))
        self.label_Vector.setText(_translate("Form", "TextLabel"))
        self.pushButton_Vector.setText(_translate("Form", "obtener vector"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
